// Action types.
export const WINDOW_DIMENSIONS = 'WINDOW_DIMENSIONS';

export const TOGGLE_LEFT_SIDEBAR = 'TOGGLE_LEFT_SIDEBAR';
export const TOGGLE_RIGHT_SIDEBAR = 'TOGGLE_RIGHT_SIDEBAR';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const CHANGE_FOLDER = 'CHANGE_FOLDER';
export const SELECT_FILE = 'SELECT_FILE';
export const SET_FILE_MANAGER_DATA = 'SET_FILE_MANAGER_DATA';

// Main Content Area constants.
export const SET_CONTENT_AREA_VIEW = 'SET_CONTENT_AREA_VIEW';
export const DEFAULT = 'DEFAULT';
export const PREVIEW = 'PREVIEW';
export const UPLOAD = 'UPLOAD';
export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const SEARCHING_FOR = 'SEARCHING_FOR';
export const DATAGRID = 'DATAGRID';
export const VERSION_HISTORY = 'VERSION_HISTORY';

// Right Panel constants.
export const SET_RIGHT_PANEL_AREA_VIEW = 'SET_RIGHT_PANEL_AREA_VIEW';
export const ACTIVITY = 'ACTIVITY';
export const DETAIL = 'DETAIL';
export const DETAIL_DRAFT = 'DETAIL_DRAFT';
export const DETAIL_SUBMITTED = 'DETAIL_SUBMITTED';
export const DETAILFORM = 'DETAILFORM';
export const VIEWER_CHANGE_REQUEST = 'VIEWER_CHANGE_REQUEST';
export const OWNERCHANGE_REQUEST = 'OWNERCHANGE_REQUEST';
export const RELEASE_NOTIFICATION = 'RELEASE_NOTIFICATION';
export const APPROVAL_WORKFLOW = 'APPROVAL_WORKFLOW';
export const PERIODIC_REVIEW = 'PERIODIC_REVIEW';

// Modal constants.
export const SET_MODAL_VIEW = 'SET_MODAL_VIEW';
export const SHARE = 'SHARE';
export const CHECKIN = 'CHECKIN';
export const CHECKOUT = 'CHECKOUT';
export const DOWNLOAD = 'DOWNLOAD';
export const UPLOAD_NEW_VERSION = 'UPLOAD_NEW_VERSION';

export const IFRAME_SOURCE = 'IFRAME_SOURCE';
export const SET_FIREBASE_URL = 'SET_FIREBASE_URL';
