// Action types.
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const CHANGE_FOLDER = 'CHANGE_FOLDER';
export const SET_FILE_MANAGER_DATA = 'SET_FILE_MANAGER_DATA';

export const COMPLETE_UPLOAD = 'COMPLETE_UPLOAD';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const IFRAME_SOURCE = 'IFRAME_SOURCE';
