// Action types.
export const WINDOW_DIMENSIONS = 'WINDOW_DIMENSIONS';

export const TOGGLE_LEFT_SIDEBAR = 'TOGGLE_LEFT_SIDEBAR';
export const TOGGLE_RIGHT_SIDEBAR = 'TOGGLE_RIGHT_SIDEBAR';

export const CHANGE_FOLDER = 'CHANGE_FOLDER';
export const SELECT_FILE = 'SELECT_FILE';
export const SET_FILE_MANAGER_DATA = 'SET_FILE_MANAGER_DATA';

// Main Content Area constants.
export const SET_CONTENT_AREA_VIEW = 'SET_CONTENT_AREA_VIEW';
export const DEFAULT = 'DEFAULT';
export const PREVIEW = 'PREVIEW';
export const UPLOAD = 'UPLOAD';
export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const SEARCHING_FOR = 'SEARCHING_FOR';

// Right Panel constants.
export const SET_RIGHT_PANEL_AREA_VIEW = 'SET_RIGHT_PANEL_AREA_VIEW';
export const ACTIVITY = 'ACTIVITY';
export const DETAIL = 'DETAIL';
export const DETAILFORM = 'DETAILFORM';
export const VIEWER_CHANGE_REQUEST = 'VIEWER_CHANGE_REQUEST';
export const OWNERCHANGE_REQUEST = 'OWNERCHANGE_REQUEST';

export const IFRAME_SOURCE = 'IFRAME_SOURCE';
